### ISSUE TITLE
小程序里可以使用吗？

### ISSUE THREAD

**Issue by williambao** [TencentCloudBase/cloudbase-js-sdk#10]
这个库可以在小程序使用吗？ 好像没有相应的adapter?
因为不想开通小程序本身那个云开发。 打算在腾讯云后台开通后使用这个js sdk。

**Comment by abearxiong** [comment]
可以用的，adapter，网上可以找到

**Comment by Mrjing** [comment]
小程序环境下需要用这个库 https://github.com/TencentCloudBase/tcb-js-sdk-mp
