### ISSUE TITLE
接口调用失败后无法获取错误码

### ISSUE THREAD

**Issue by ZhenlyChen** [TencentCloudBase/cloudbase-js-sdk#11]
问题描述：调用SDK中方法，在抛出的错误中无法获取错误码和错误信息

环境：React

```js
try {
  const res = await server.auth.signUpWithEmailAndPassword(form.email, form.password)
  console.log(res)
} catch (err) {
  console.log(err)
  console.log("错误描述：" + err.message)
}
```

预期得到 `[INVALID_PARAM] [100003] mail addr is invalid` 
![image](https://user-images.githubusercontent.com/20028311/115270201-aadcbe80-a16e-11eb-82cd-28374c5599f8.png)

调试源码发现抛出的异常把code和message都去掉了，这样做是否有什么原因？目前代码中无法获取到具体的错误详情，无法针对错误对业务做具体的展示。
![image](https://user-images.githubusercontent.com/20028311/115270129-9c8ea280-a16e-11eb-8fe0-1ad08a1e8f4f.png)

**Comment by Mrjing** [comment]
麻烦更新到@cloudbase/js-sdk@1.7.0版本，已修复该问题。
