### ISSUE TITLE
缺少文档链接

### ISSUE THREAD

**Issue by lgh06** [TencentCloudBase/cloudbase-js-sdk#12]
建议把
https://docs.cloudbase.net/api-reference/webv2/initialization.html   

以及相关文档链接：
https://cloud.tencent.com/document/product/876/19369  
https://cloud.tencent.com/document/product/876/46332  
写在readme里。

**Comment by binggg** [comment]
@Mrjing

**Comment by Mrjing** [comment]
文档问题已处理
