### ISSUE TITLE
建议支持ts

### ISSUE THREAD

**Issue by webszy** [TencentCloudBase/cloudbase-js-sdk#2]

**Comment by zhoujunpeng** [comment]
支持ts啊，有遇到什么具体问题吗？

**Comment by webszy** [comment]
提示找不到类型文件

**Comment by zhoujunpeng** [comment]
具体的使用场景可以描述一下吗？sdk是支持ts的
![image](https://user-images.githubusercontent.com/6055397/96823196-82ddfe00-145e-11eb-96ba-3568ddc3f5b2.png)

**Comment by webszy** [comment]
sorry，应该是编辑器问题
