### ISSUE TITLE
云存储的上传文件对象的filePath属性类型错误

### ISSUE THREAD

**Issue by lzxjack** [TencentCloudBase/cloudbase-js-sdk#24]
下面是云开发文档：
```JavaScript
app
  .uploadFile({
    // 云存储的路径
    cloudPath: "dirname/filename",
    // 需要上传的文件，File 类型
    filePath: document.getElementById("file").files[0]
  })
  .then((res) => {
    // 返回文件 ID
    console.log(res.fileID);
  });
```

`filePath`在云开发文档里写的要 File 类型，实际上依赖包里定义的是 string。使用 TS 上传文件会有类型错误。

![](https://jack-img.oss-cn-hangzhou.aliyuncs.com/img/20211221093659.png)

**Comment by nomentech** [comment]
确实，用TS开发的话目前的解决方案只有把代入filePath的文件类型设置成any. document.getElementById("file").files[0] 获得的是File类型，设置成any可以跳过这个类型错误。
