### ISSUE TITLE
浏览器环境报错：Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by LinFeng1997** [TencentCloudBase/cloudbase-js-sdk#3]
代码：
```js
// 内核
import cloudbase from "@cloudbase/js-sdk/app";
// 数据库模块
import "@cloudbase/js-sdk/database";

const config = {
    env: "test-19a220" // 前往「腾讯云控制台」-「云开发 CloudBase」获取
};
const app = cloudbase.init(config);

const db = app.database();
console.log('db',db);
```

**Comment by LinFeng1997** [comment]
@cloudbase/js-sdk 版本 1.3.3

**Comment by zhoujunpeng** [comment]
@LinFeng1997 你好，我试了下没有复现这个报错，方便的话麻烦尽量提供一下完整的代码，包括webpack的配置

**Comment by LinFeng1997** [comment]
@zhoujunpeng 已解决，的确是因为 webpack 配置，你们的 sdk 默认注入了 global 变量，但是 webpack 3 以后已经默认未内置 `global: true` 这个配置

![image](https://user-images.githubusercontent.com/16188742/97866418-d695f480-1d46-11eb-9822-eeb3607cf42f.png)

希望你们的文档补充说明下这点，以便后人使用

**Comment by zhoujunpeng** [comment]
@LinFeng1997 好的，感谢反馈
